//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMIDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMI_Treasury
    {
        public int Id { get; set; }
        public int IDChurch { get; set; }
        public string TreasuryMonth { get; set; }
        public int IDUser { get; set; }
        public Nullable<System.DateTime> TreasuryDate { get; set; }
    
        public virtual SMI_Church SMI_Church { get; set; }
        public virtual SMI_User SMI_User { get; set; }
        public virtual SMI_TreasuryDetail SMI_TreasuryDetail { get; set; }
    }
}
