//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMIDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMI_CountryChurch
    {
        public int ID { get; set; }
        public Nullable<int> IdCountry { get; set; }
        public Nullable<int> IdChurch { get; set; }
    
        public virtual SMI_Church SMI_Church { get; set; }
        public virtual SMI_Country SMI_Country { get; set; }
    }
}
