//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMIDA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DefaultConnection : DbContext
    {
        public DefaultConnection()
            : base("name=DefaultConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SMI_Church> SMI_Church { get; set; }
        public virtual DbSet<SMI_Country> SMI_Country { get; set; }
        public virtual DbSet<SMI_CountryChurch> SMI_CountryChurch { get; set; }
        public virtual DbSet<SMI_Treasury> SMI_Treasury { get; set; }
        public virtual DbSet<SMI_TreasuryDetail> SMI_TreasuryDetail { get; set; }
        public virtual DbSet<SMI_User> SMI_User { get; set; }
    }
}
